package machine;

public enum CoffeMachineState {
    GROUND_STATE,
    GET_MAIN_MENU,
    GET_COFFEE_MENU,
    COFFEE_MENU,
    FILLING_WATER,
    FILLING_COFFEE,
    FILLING_MILK,
    FILLING_CUPS,
    FILLING_WATER_MENU,
    FILLING_COFFEE_MENU,
    FILLING_MILK_MENU,
    FILLING_CUPS_MENU
}
